# Generated by Django 3.2.17 on 2023-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Paid_leaves',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='Employee_Signature_Photo',
            field=models.ImageField(default='', null=True, upload_to='Employee_Sign'),
        ),
    ]
